name: Build and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Check out the repository
      uses: actions/checkout@v4
      with:
        ref: ${{ github.head_ref }}

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm i

    - name: Compile with tsup
      run: npx tsup

    - name: Commit compiled files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        commit_message: Build and push compiled files
